# Generated by Django 5.1.4 on 2026-05-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='About Us', max_length=100)),
                ('heading', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('btn_text', models.CharField(blank=True, max_length=100)),
                ('btn_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=400)),
                ('btn1_text', models.CharField(blank=True, max_length=100, verbose_name='Button 1 Text')),
                ('btn1_link', models.URLField(blank=True, verbose_name='Button 1 Link')),
                ('btn2_text', models.CharField(blank=True, max_length=100, verbose_name='Button 2 Text')),
                ('btn2_link', models.URLField(blank=True, verbose_name='Button 2 Link')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner Slide',
                'verbose_name_plural': 'Banner Slides',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTABanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('subheading', models.CharField(blank=True, max_length=400)),
                ('btn_text', models.CharField(max_length=100)),
                ('btn_link', models.URLField()),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='cta/')),
            ],
            options={
                'verbose_name': 'CTA Banner',
                'verbose_name_plural': 'CTA Banner',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='features/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed_url', models.TextField(help_text='Google Maps embed src URL')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(default='© 2025 Paramita Schools. All Rights Reserved.', max_length=300)),
            ],
            options={
                'verbose_name': 'Footer Information',
                'verbose_name_plural': 'Footer Information',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='INTRODUCTION', max_length=100)),
                ('heading', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='intro/')),
            ],
            options={
                'verbose_name': 'Introduction Section',
                'verbose_name_plural': 'Introduction Section',
            },
        ),
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(default='Dear Parents, Students, and Esteemed Staff Members,', max_length=200)),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(default='Principal', max_length=200)),
                ('image', models.ImageField(upload_to='principal/')),
                ('btn_text', models.CharField(default='Know More', max_length=100)),
                ('btn_link', models.URLField(blank=True, default='#')),
            ],
            options={
                'verbose_name': 'Principal Message',
                'verbose_name_plural': 'Principal Message',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Main navbar logo', upload_to='site/')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('parent_login_url', models.URLField(blank=True, default='#')),
                ('tagline', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube')], default='instagram', max_length=20)),
                ('image', models.ImageField(upload_to='social/')),
                ('link', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Feed Post',
                'verbose_name_plural': 'Social Feed Posts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('review', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.navmenuitem')),
            ],
            options={
                'verbose_name': 'Nav Menu Item',
                'verbose_name_plural': 'Nav Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
