# Generated by Django 5.1.4 on 2026-06-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalmessage',
            name='image_style',
            field=models.CharField(choices=[('circle', 'Circle — Classic round portrait'), ('square', 'Square — Sharp professional look'), ('rounded', 'Rounded Square — Modern soft edges'), ('hexagon', 'Hexagon — Unique geometric frame')], default='circle', help_text='Choose the shape of the principal photo frame', max_length=20, verbose_name='Image Frame Style'),
        ),
        migrations.AlterField(
            model_name='principalmessage',
            name='btn_link',
            field=models.CharField(blank=True, default='#', help_text='e.g. / or https://example.com', max_length=300),
        ),
    ]
