# Generated by Django 5.1.4 on 2026-06-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_principalmessage_image_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialfeed',
            name='custom_platform',
            field=models.CharField(blank=True, help_text='Specify platform name if "Other" is selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialfeed',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('other', 'Other')], default='instagram', max_length=20),
        ),
    ]
